# Generated by Django 4.1.7 on 2023-03-02 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_name_user_avatar_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be in the format "+999 999-9999".',
                        regex="^\\+?\\d{1,3}[\\d\\s-]{5,}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
