# Generated by Django 4.1.7 on 2023-03-10 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_avatar_alter_user_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="date_of_birth",
            new_name="birthday",
        ),
        migrations.AddField(
            model_name="user",
            name="metamask_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Metamask подтвержден"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="token_balance",
            field=models.PositiveIntegerField(default=0, verbose_name="Баланс токенов"),
        ),
    ]
