# Generated by Django 4.1.7 on 2023-03-12 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_rename_settings_usersettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"]},
        ),
    ]
