# Generated by Django 4.1.7 on 2023-03-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_user_metamask_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="metamask_wallet",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Metamask",
            ),
        ),
    ]
