# Generated by Django 4.1.5 on 2023-01-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
                ('buyer_wallet_id', models.CharField(max_length=255)),
                ('seller_id', models.IntegerField()),
                ('seller_wallet_id', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('sum', models.CharField(max_length=255)),
                ('reward', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TokenReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
                ('buyer_wallet_id', models.CharField(max_length=255)),
                ('referral_id', models.IntegerField()),
                ('referral_wallet_id', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('reward', models.CharField(max_length=255)),
            ],
        ),
    ]
