# Generated by Django 4.1.7 on 2023-03-11 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="# Раунд", max_length=50, verbose_name="Название"
                    ),
                ),
                (
                    "percent_share",
                    models.PositiveSmallIntegerField(verbose_name="Доля"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("$", "USD")],
                        default="$",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="Цена"
                    ),
                ),
                (
                    "total_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Токенов в раунде"
                    ),
                ),
                (
                    "total_amount_sold",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Продано в раунде"
                    ),
                ),
                (
                    "progress",
                    models.FloatField(default=0, verbose_name="Прогресс раунда"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активен"),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="Завершен"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Token Round",
                "verbose_name_plural": "Token Rounds",
                "ordering": ["unit_price"],
            },
        ),
        migrations.CreateModel(
            name="TokenTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "reward",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Награда"
                    ),
                ),
                (
                    "reward_sent",
                    models.BooleanField(
                        default=False, verbose_name="Награда начислена"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "token_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="tokens.tokenround",
                        verbose_name="Раунд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Transaction",
                "verbose_name_plural": "Token Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        default="Token",
                        max_length=50,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "total_amount",
                    models.PositiveBigIntegerField(verbose_name="Всего токенов"),
                ),
                (
                    "total_amount_sold",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Продано токенов"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tokens.tokenround",
                        verbose_name="Активный раунд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
            },
        ),
    ]
