# Generated by Django 4.1.7 on 2023-03-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="name",
            field=models.CharField(
                default="Token", max_length=50, verbose_name="Название"
            ),
        ),
    ]
