# Generated by Django 4.1.7 on 2023-03-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0002_alter_token_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="total_amount_sold",
        ),
        migrations.AlterField(
            model_name="token",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление"
            ),
        ),
    ]
