# Generated by Django 4.1.7 on 2023-03-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0003_remove_token_total_amount_sold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenround",
            name="progress",
        ),
        migrations.AddField(
            model_name="tokentransaction",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена токенов"
            ),
            preserve_default=False,
        ),
    ]
