# Generated by Django 4.1.7 on 2023-03-14 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0006_remove_tokenround_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokentransaction",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="tokenround",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление"
            ),
        ),
        migrations.AlterField(
            model_name="tokentransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создана в"),
        ),
        migrations.AlterField(
            model_name="tokentransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("failed", "Failed"),
                    ("success", "Success"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
