# Generated by Django 4.1.7 on 2023-03-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0007_tokentransaction_uuid_alter_tokenround_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokentransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("failed", "Failed"),
                    ("success", "Success"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
