# Generated by Django 4.1.7 on 2023-03-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0008_alter_tokentransaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenround",
            name="unit_price",
            field=models.DecimalField(
                db_index=True, decimal_places=3, max_digits=6, verbose_name="Цена"
            ),
        ),
    ]
