# Generated by Django 4.1.7 on 2023-03-20 20:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("tokens", "0011_tokentransactionraw"),
        ("tokens", "0012_rename_blockhash_tokentransactionraw_block_hash_and_more"),
        ("tokens", "0013_alter_tokentransactionraw_address"),
        ("tokens", "0014_alter_tokentransactionraw_block_hash_and_more"),
        ("tokens", "0015_alter_tokentransactionraw_options_and_more"),
    ]

    dependencies = [
        ("tokens", "0010_alter_tokentransaction_buyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenTransactionRaw",
            fields=[
                ("address", models.CharField(max_length=100)),
                (
                    "topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=4
                    ),
                ),
                ("data", models.CharField(max_length=100)),
                ("block_number", models.CharField(max_length=100)),
                ("block_hash", models.CharField(max_length=66)),
                ("time_stamp", models.DateTimeField()),
                ("gas_price", models.CharField(max_length=100)),
                ("gas_used", models.CharField(max_length=100)),
                ("log_index", models.CharField(max_length=100)),
                (
                    "transaction_hash",
                    models.CharField(
                        db_index=True,
                        max_length=66,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("transaction_index", models.CharField(max_length=100)),
                (
                    "block_chain",
                    models.CharField(
                        choices=[("bscscan", "bscscan")],
                        db_index=True,
                        default="bscscan",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-time_stamp"],
                "verbose_name": "Token Transaction Raw",
                "verbose_name_plural": "Token Transactions Raw",
            },
        ),
    ]
