# Generated by Django 4.1.7 on 2023-03-27 10:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("tokens", "0011_tokentransaction_tx_hash_and_more"),
        ("tokens", "0012_tokentransaction_buyer_address"),
        ("tokens", "0013_alter_tokentransactionraw_options"),
        ("tokens", "0014_alter_tokentransactionraw_options"),
    ]

    dependencies = [
        ("tokens", "0010_alter_tokentransaction_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokentransaction",
            name="tx_hash",
            field=models.CharField(
                db_index=True, default=1, editable=False, max_length=70, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tokentransaction",
            name="tx_log_index",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tokentransaction",
            name="created_at",
            field=models.DateTimeField(verbose_name="Создана в"),
        ),
        migrations.AlterUniqueTogether(
            name="tokentransaction",
            unique_together={("tx_hash", "tx_log_index")},
        ),
        migrations.RemoveField(
            model_name="tokentransaction",
            name="uuid",
        ),
        migrations.AddField(
            model_name="tokentransaction",
            name="buyer_address",
            field=models.CharField(db_index=True, default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TokenTransactionRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                (
                    "topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=4
                    ),
                ),
                ("data", models.TextField()),
                ("block_number", models.CharField(max_length=100)),
                ("block_hash", models.CharField(max_length=66)),
                ("time_stamp", models.DateTimeField()),
                ("gas_price", models.CharField(max_length=100)),
                ("gas_used", models.CharField(max_length=100)),
                ("log_index", models.CharField(max_length=100)),
                ("transaction_hash", models.CharField(db_index=True, max_length=66)),
                ("transaction_index", models.CharField(max_length=100)),
                (
                    "block_chain",
                    models.CharField(
                        choices=[("bscscan", "bscscan")],
                        db_index=True,
                        default="bscscan",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Transaction Raw",
                "verbose_name_plural": "Token Transactions Raw",
                "ordering": ["-time_stamp"],
                "unique_together": {("transaction_hash", "log_index")},
            },
        ),
    ]
