# Generated by Django 4.1.7 on 2023-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tokens",
            "0011_tokentransaction_tx_hash_and_more_squashed_0014_alter_tokentransactionraw_options",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tokentransaction",
            name="reward_type",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("admin", "Admin")],
                db_index=True,
                default="buyer",
                max_length=20,
                verbose_name="Тип награды",
            ),
        ),
    ]
